version: "3.6"

networks:
  proxy_default:
    external: true

  node-mqtt-transponder:
    external: false
    name: ${PROJECT_NAME}

  node-mqtt-transponder_tunnel:
    external: false
    name: ${PROJECT_NAME}_tunnel

services:

  node-mqtt-transponder_server:
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    image: ${PROJECT_NAME}_server
    working_dir: /node-mqtt-transponder/server
    container_name: ${PROJECT_NAME}_server

    # start the container, not the server
    command: 'tail -f /dev/null'

    user: root
    volumes:
      - .:/node-mqtt-transponder
    networks:
      - proxy_default
      - node-mqtt-transponder
      - node-mqtt-transponder_tunnel
    extra_hosts:
      - "host:${HOST_IP}"
    environment:
      - DEBUG=true
      - ENVIRONMENT=default
      - NODE_ENV=development
      - SERVER_FRONTEND_PATH=../frontend/dist/dev

      # reverse proxy (not included)
      - VIRTUAL_HOST=${PROJECT_NAME}.${HOST_NAME}
      - VIRTUAL_PORT=${SERVER_PORT}
      - HOST_IP=${HOST_IP}
