version: "3.6"

networks:
  proxy_default:
    external: true

  node-mqtt-transponder:
    external: false
    name: ${PROJECT_NAME}

  node-mqtt-transponder_tunnel:
    external: false
    name: ${PROJECT_NAME}_tunnel

services:

  node-mqtt-transponder_server:
    restart: always
    build:
      context: .
      dockerfile: server/Dockerfile
    image: ${PROJECT_NAME}_server
    working_dir: /node-mqtt-transponder/server
    container_name: ${PROJECT_NAME}_server
    command: "--experimental-modules --experimental-json-modules index.js"
    user: root
    volumes:
      # override the example config
      - ./server/config:/node-mqtt-transponder/server/config

      # override example .env in container
      - ./.env:/node-mqtt-transponder/.env

      # mount the frontend production bundle into the container
      - ./frontend/dist/prod:/node-mqtt-transponder/server/frontend
    networks:
      - proxy_default
      - node-mqtt-transponder
      - node-mqtt-transponder_tunnel
    extra_hosts:
      - "host:${HOST_IP}"
    environment:

      # disable console logging
      - DEBUG=true

      # change it to another environment
      # the name equals a file with .conf in server/config
      - ENVIRONMENT=default

      # don't know why, but ...
      - NODE_ENV=production

      # this is the mounted volume path in the container
      - SERVER_FRONTEND_PATH=frontend

      # internal local use for jwilders reverse proxy and dockergen
      - VIRTUAL_HOST=${PROJECT_NAME}.${HOST_NAME}
      - VIRTUAL_PORT=${SERVER_PORT}
      - HOST_IP=${HOST_IP}
